# Generated by Django 3.2 on 2021-05-05 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_testmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
